version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  app:
    build: .
    volumes:
      - ./dist:/usr/src/app
    links:
      - db:${POSTGRES_HOST}
    ports:
      - 8080:3000
    depends_on:
      - db
